"""Pre-seeded starter recipes for new installations.

Provides ~20 recipes covering breakfast, lunch, dinner, and snack categories
so the app feels useful on first launch. Only seeds when the recipes table is empty.
"""

from meal_planner.db.database import get_connection
from meal_planner.db.models import Recipe, RecipeIngredient


STARTER_RECIPES = [
    # === BREAKFAST (4) ===
    {
        "name": "Classic Oatmeal with Berries",
        "description": "Warm and hearty oatmeal topped with fresh berries and honey.",
        "servings": 2,
        "prep_time": "5 minutes",
        "cook_time": "10 minutes",
        "tags": "breakfast,quick,easy,healthy,vegetarian",
        "rating": 4,
        "instructions": "1. Bring 2 cups water to a boil.\n2. Add oats and reduce heat to medium-low.\n3. Cook for 5 minutes, stirring occasionally.\n4. Top with berries, a drizzle of honey, and a pinch of cinnamon.",
        "ingredients": [
            {"name": "rolled oats", "quantity": 1, "unit": "cup"},
            {"name": "mixed berries", "quantity": 1, "unit": "cup"},
            {"name": "honey", "quantity": 1, "unit": "tbsp"},
            {"name": "cinnamon", "quantity": 1, "unit": "pinch"},
        ],
    },
    {
        "name": "Scrambled Eggs with Toast",
        "description": "Fluffy scrambled eggs served with buttered toast.",
        "servings": 2,
        "prep_time": "5 minutes",
        "cook_time": "5 minutes",
        "tags": "breakfast,quick,easy,kid-friendly",
        "rating": 4,
        "instructions": "1. Crack eggs into a bowl and whisk with milk, salt, and pepper.\n2. Melt butter in a non-stick pan over medium-low heat.\n3. Pour in eggs and gently stir with a spatula until just set.\n4. Serve immediately with buttered toast.",
        "ingredients": [
            {"name": "eggs", "quantity": 4, "unit": None},
            {"name": "milk", "quantity": 2, "unit": "tbsp"},
            {"name": "butter", "quantity": 1, "unit": "tbsp"},
            {"name": "bread", "quantity": 4, "unit": "slice"},
        ],
    },
    {
        "name": "Banana Pancakes",
        "description": "Fluffy pancakes made with ripe bananas for natural sweetness.",
        "servings": 4,
        "prep_time": "10 minutes",
        "cook_time": "15 minutes",
        "tags": "breakfast,kid-friendly,vegetarian",
        "rating": 5,
        "instructions": "1. Mash bananas in a large bowl.\n2. Add eggs, milk, and melted butter. Mix well.\n3. In a separate bowl, whisk flour, baking powder, and salt.\n4. Combine wet and dry ingredients until just mixed.\n5. Cook on a greased griddle over medium heat, about 3 minutes per side.\n6. Serve with maple syrup.",
        "ingredients": [
            {"name": "ripe bananas", "quantity": 2, "unit": None},
            {"name": "eggs", "quantity": 2, "unit": None},
            {"name": "milk", "quantity": 1, "unit": "cup"},
            {"name": "all-purpose flour", "quantity": 1.5, "unit": "cups"},
            {"name": "baking powder", "quantity": 2, "unit": "tsp"},
            {"name": "butter", "quantity": 2, "unit": "tbsp"},
        ],
    },
    {
        "name": "Yogurt Parfait",
        "description": "Layered Greek yogurt with granola and fresh fruit.",
        "servings": 1,
        "prep_time": "5 minutes",
        "cook_time": "0 minutes",
        "tags": "breakfast,quick,easy,healthy,vegetarian",
        "rating": 4,
        "instructions": "1. Spoon a layer of yogurt into a glass or bowl.\n2. Add a layer of granola.\n3. Add a layer of mixed berries.\n4. Repeat layers.\n5. Drizzle with honey and serve.",
        "ingredients": [
            {"name": "Greek yogurt", "quantity": 1, "unit": "cup"},
            {"name": "granola", "quantity": 0.5, "unit": "cup"},
            {"name": "mixed berries", "quantity": 0.5, "unit": "cup"},
            {"name": "honey", "quantity": 1, "unit": "tsp"},
        ],
    },
    # === LUNCH (4) ===
    {
        "name": "Chicken Caesar Salad",
        "description": "Crisp romaine lettuce with grilled chicken, croutons, and Caesar dressing.",
        "servings": 2,
        "prep_time": "15 minutes",
        "cook_time": "10 minutes",
        "tags": "lunch,salad,healthy,high-protein",
        "rating": 4,
        "instructions": "1. Season chicken breast with salt and pepper.\n2. Grill or pan-sear chicken for 5-6 minutes per side until cooked through.\n3. Slice chicken and let rest.\n4. Chop romaine lettuce and place in a large bowl.\n5. Add croutons, Parmesan, and sliced chicken.\n6. Toss with Caesar dressing and serve.",
        "ingredients": [
            {"name": "chicken breast", "quantity": 1, "unit": "lb"},
            {"name": "romaine lettuce", "quantity": 1, "unit": None},
            {"name": "Caesar dressing", "quantity": 0.25, "unit": "cup"},
            {"name": "croutons", "quantity": 0.5, "unit": "cup"},
            {"name": "Parmesan cheese", "quantity": 0.25, "unit": "cup"},
        ],
    },
    {
        "name": "Black Bean Quesadillas",
        "description": "Crispy tortillas filled with black beans, cheese, and peppers.",
        "servings": 4,
        "prep_time": "10 minutes",
        "cook_time": "10 minutes",
        "tags": "lunch,quick,easy,vegetarian,kid-friendly,budget-friendly",
        "rating": 4,
        "instructions": "1. Drain and rinse black beans.\n2. Dice bell pepper and onion.\n3. Lay tortillas flat. Spread beans on half of each.\n4. Top with cheese, peppers, and onion.\n5. Fold tortillas in half.\n6. Cook in a skillet over medium heat, 3 minutes per side until golden and cheese melts.\n7. Cut into wedges. Serve with salsa and sour cream.",
        "ingredients": [
            {"name": "flour tortillas", "quantity": 4, "unit": None},
            {"name": "black beans", "quantity": 1, "unit": "can"},
            {"name": "shredded cheese", "quantity": 1, "unit": "cup"},
            {"name": "bell pepper", "quantity": 1, "unit": None},
            {"name": "onion", "quantity": 0.5, "unit": None},
            {"name": "salsa", "quantity": 0.5, "unit": "cup"},
        ],
    },
    {
        "name": "Tomato Soup with Grilled Cheese",
        "description": "Classic comfort food pairing of creamy tomato soup and grilled cheese sandwiches.",
        "servings": 4,
        "prep_time": "10 minutes",
        "cook_time": "25 minutes",
        "tags": "lunch,soup,comfort food,vegetarian,kid-friendly",
        "rating": 5,
        "instructions": "1. Dice onion and mince garlic. Saute in olive oil until soft.\n2. Add crushed tomatoes, broth, salt, pepper, and a pinch of sugar.\n3. Simmer for 15 minutes. Blend until smooth.\n4. Stir in cream.\n5. For sandwiches: butter bread, add cheese, cook in skillet until golden on both sides.\n6. Serve soup in bowls with grilled cheese on the side.",
        "ingredients": [
            {"name": "crushed tomatoes", "quantity": 2, "unit": "cans"},
            {"name": "chicken broth", "quantity": 1, "unit": "cup"},
            {"name": "onion", "quantity": 1, "unit": None},
            {"name": "garlic", "quantity": 2, "unit": "cloves"},
            {"name": "heavy cream", "quantity": 0.25, "unit": "cup"},
            {"name": "bread", "quantity": 8, "unit": "slice"},
            {"name": "cheddar cheese", "quantity": 8, "unit": "slice"},
            {"name": "butter", "quantity": 3, "unit": "tbsp"},
        ],
    },
    {
        "name": "Tuna Salad Wraps",
        "description": "Light and protein-packed tuna salad in whole wheat wraps.",
        "servings": 2,
        "prep_time": "10 minutes",
        "cook_time": "0 minutes",
        "tags": "lunch,quick,easy,high-protein,meal-prep",
        "rating": 3,
        "instructions": "1. Drain tuna and place in a bowl.\n2. Add mayo, mustard, diced celery, salt, and pepper. Mix well.\n3. Lay wraps flat and divide tuna mixture between them.\n4. Add lettuce and tomato slices.\n5. Roll up tightly and slice in half.",
        "ingredients": [
            {"name": "canned tuna", "quantity": 2, "unit": "cans"},
            {"name": "mayonnaise", "quantity": 2, "unit": "tbsp"},
            {"name": "Dijon mustard", "quantity": 1, "unit": "tsp"},
            {"name": "celery", "quantity": 1, "unit": None},
            {"name": "whole wheat wraps", "quantity": 2, "unit": None},
            {"name": "lettuce leaves", "quantity": 4, "unit": None},
        ],
    },
    # === DINNER (9) ===
    {
        "name": "Spaghetti Bolognese",
        "description": "Classic Italian meat sauce over spaghetti pasta.",
        "servings": 6,
        "prep_time": "15 minutes",
        "cook_time": "45 minutes",
        "tags": "dinner,comfort food,kid-friendly,meal-prep",
        "rating": 5,
        "instructions": "1. Brown ground beef in a large pot, breaking into small pieces. Drain excess fat.\n2. Add diced onion, minced garlic, and diced carrots. Cook 5 minutes.\n3. Add crushed tomatoes, tomato paste, Italian seasoning, salt, and pepper.\n4. Simmer on low for 30 minutes, stirring occasionally.\n5. Cook spaghetti according to package directions. Drain.\n6. Serve sauce over pasta. Top with Parmesan cheese.",
        "ingredients": [
            {"name": "ground beef", "quantity": 1.5, "unit": "lbs"},
            {"name": "spaghetti", "quantity": 1, "unit": "lb"},
            {"name": "crushed tomatoes", "quantity": 2, "unit": "cans"},
            {"name": "tomato paste", "quantity": 2, "unit": "tbsp"},
            {"name": "onion", "quantity": 1, "unit": None},
            {"name": "garlic", "quantity": 3, "unit": "cloves"},
            {"name": "carrot", "quantity": 1, "unit": None},
            {"name": "Italian seasoning", "quantity": 1, "unit": "tbsp"},
        ],
    },
    {
        "name": "Chicken Stir-Fry",
        "description": "Quick and colorful chicken stir-fry with mixed vegetables.",
        "servings": 4,
        "prep_time": "15 minutes",
        "cook_time": "10 minutes",
        "tags": "dinner,quick,easy,healthy,high-protein",
        "rating": 4,
        "instructions": "1. Slice chicken into thin strips. Season with salt and pepper.\n2. Heat oil in a wok or large skillet over high heat.\n3. Cook chicken 4-5 minutes until golden. Remove and set aside.\n4. Add vegetables to the pan and stir-fry 3-4 minutes.\n5. Return chicken. Add soy sauce, sesame oil, and ginger.\n6. Toss to combine. Serve over steamed rice.",
        "ingredients": [
            {"name": "chicken breast", "quantity": 1.5, "unit": "lbs"},
            {"name": "broccoli florets", "quantity": 2, "unit": "cups"},
            {"name": "bell pepper", "quantity": 1, "unit": None},
            {"name": "snap peas", "quantity": 1, "unit": "cup"},
            {"name": "soy sauce", "quantity": 3, "unit": "tbsp"},
            {"name": "sesame oil", "quantity": 1, "unit": "tsp"},
            {"name": "fresh ginger", "quantity": 1, "unit": "tbsp"},
            {"name": "rice", "quantity": 2, "unit": "cups"},
        ],
    },
    {
        "name": "Beef Tacos",
        "description": "Seasoned ground beef tacos with all the classic fixings.",
        "servings": 4,
        "prep_time": "10 minutes",
        "cook_time": "15 minutes",
        "tags": "dinner,quick,easy,kid-friendly",
        "rating": 5,
        "instructions": "1. Brown ground beef in a skillet. Drain fat.\n2. Add taco seasoning and water per packet instructions. Simmer 5 minutes.\n3. Warm taco shells according to package.\n4. Fill shells with beef.\n5. Top with shredded cheese, lettuce, diced tomato, and sour cream.\n6. Serve with lime wedges.",
        "ingredients": [
            {"name": "ground beef", "quantity": 1, "unit": "lb"},
            {"name": "taco seasoning", "quantity": 1, "unit": "pkg"},
            {"name": "taco shells", "quantity": 12, "unit": None},
            {"name": "shredded cheese", "quantity": 1, "unit": "cup"},
            {"name": "lettuce", "quantity": 2, "unit": "cups"},
            {"name": "tomato", "quantity": 2, "unit": None},
            {"name": "sour cream", "quantity": 0.5, "unit": "cup"},
        ],
    },
    {
        "name": "Baked Salmon with Roasted Vegetables",
        "description": "Oven-baked salmon fillets with a medley of roasted seasonal vegetables.",
        "servings": 4,
        "prep_time": "15 minutes",
        "cook_time": "25 minutes",
        "tags": "dinner,healthy,high-protein,gluten-free",
        "rating": 5,
        "instructions": "1. Preheat oven to 400°F (200°C).\n2. Place salmon fillets on a lined baking sheet.\n3. Season with olive oil, lemon juice, garlic, salt, and pepper.\n4. On a separate sheet, toss broccoli, bell pepper, and zucchini with olive oil and seasoning.\n5. Bake salmon 12-15 minutes and vegetables 20-25 minutes.\n6. Serve salmon over vegetables with lemon wedges.",
        "ingredients": [
            {"name": "salmon fillets", "quantity": 4, "unit": None},
            {"name": "broccoli", "quantity": 2, "unit": "cups"},
            {"name": "bell pepper", "quantity": 1, "unit": None},
            {"name": "zucchini", "quantity": 1, "unit": None},
            {"name": "olive oil", "quantity": 3, "unit": "tbsp"},
            {"name": "lemon", "quantity": 1, "unit": None},
            {"name": "garlic", "quantity": 2, "unit": "cloves"},
        ],
    },
    {
        "name": "One-Pot Chicken and Rice",
        "description": "Comforting chicken and rice cooked together in a single pot.",
        "servings": 4,
        "prep_time": "10 minutes",
        "cook_time": "35 minutes",
        "tags": "dinner,one-pot,easy,comfort food,kid-friendly",
        "rating": 4,
        "instructions": "1. Season chicken thighs with salt, pepper, and paprika.\n2. Heat oil in a large pot. Brown chicken on both sides, 3 min each. Remove.\n3. Saute diced onion and garlic until soft.\n4. Add rice and stir 1 minute.\n5. Pour in chicken broth. Place chicken on top.\n6. Cover and simmer 20-25 minutes until rice is tender and chicken is cooked through.\n7. Fluff rice with a fork and serve.",
        "ingredients": [
            {"name": "chicken thighs", "quantity": 4, "unit": None},
            {"name": "long grain rice", "quantity": 1.5, "unit": "cups"},
            {"name": "chicken broth", "quantity": 2.5, "unit": "cups"},
            {"name": "onion", "quantity": 1, "unit": None},
            {"name": "garlic", "quantity": 3, "unit": "cloves"},
            {"name": "paprika", "quantity": 1, "unit": "tsp"},
        ],
    },
    {
        "name": "Vegetable Curry",
        "description": "Rich and aromatic coconut curry loaded with vegetables.",
        "servings": 4,
        "prep_time": "15 minutes",
        "cook_time": "25 minutes",
        "tags": "dinner,vegetarian,vegan,healthy,gluten-free,one-pot",
        "rating": 4,
        "instructions": "1. Heat oil in a large pot. Saute diced onion and garlic until soft.\n2. Add curry paste and cook 1 minute until fragrant.\n3. Add diced potatoes, carrots, and chickpeas.\n4. Pour in coconut milk and vegetable broth. Stir well.\n5. Simmer 20 minutes until potatoes are tender.\n6. Stir in spinach until wilted. Season with salt.\n7. Serve over steamed rice.",
        "ingredients": [
            {"name": "coconut milk", "quantity": 1, "unit": "can"},
            {"name": "curry paste", "quantity": 2, "unit": "tbsp"},
            {"name": "potatoes", "quantity": 2, "unit": None},
            {"name": "carrots", "quantity": 2, "unit": None},
            {"name": "chickpeas", "quantity": 1, "unit": "can"},
            {"name": "spinach", "quantity": 2, "unit": "cups"},
            {"name": "onion", "quantity": 1, "unit": None},
            {"name": "vegetable broth", "quantity": 0.5, "unit": "cup"},
            {"name": "rice", "quantity": 2, "unit": "cups"},
        ],
    },
    {
        "name": "Slow Cooker Beef Stew",
        "description": "Hearty beef stew with potatoes and vegetables, slow cooked to perfection.",
        "servings": 6,
        "prep_time": "20 minutes",
        "cook_time": "8 hours",
        "tags": "dinner,slow-cooker,comfort food,meal-prep",
        "rating": 5,
        "instructions": "1. Cut beef into 1-inch cubes. Toss with flour, salt, and pepper.\n2. Brown beef in a skillet with oil (in batches). Transfer to slow cooker.\n3. Add diced potatoes, carrots, celery, and onion to the slow cooker.\n4. Pour in beef broth, tomato paste, and Worcestershire sauce.\n5. Add thyme and bay leaf.\n6. Cook on low for 7-8 hours or high for 4-5 hours.\n7. Remove bay leaf. Season to taste and serve.",
        "ingredients": [
            {"name": "beef stew meat", "quantity": 2, "unit": "lbs"},
            {"name": "potatoes", "quantity": 3, "unit": None},
            {"name": "carrots", "quantity": 3, "unit": None},
            {"name": "celery", "quantity": 2, "unit": None},
            {"name": "onion", "quantity": 1, "unit": None},
            {"name": "beef broth", "quantity": 3, "unit": "cups"},
            {"name": "tomato paste", "quantity": 2, "unit": "tbsp"},
            {"name": "Worcestershire sauce", "quantity": 1, "unit": "tbsp"},
            {"name": "all-purpose flour", "quantity": 0.25, "unit": "cup"},
        ],
    },
    {
        "name": "Pasta Primavera",
        "description": "Penne pasta tossed with sauteed seasonal vegetables in a light garlic olive oil sauce.",
        "servings": 4,
        "prep_time": "15 minutes",
        "cook_time": "15 minutes",
        "tags": "dinner,vegetarian,quick,easy,healthy",
        "rating": 4,
        "instructions": "1. Cook penne according to package directions. Reserve 1/2 cup pasta water. Drain.\n2. Heat olive oil in a large skillet. Saute garlic 30 seconds.\n3. Add zucchini, bell pepper, cherry tomatoes, and mushrooms. Cook 5-6 minutes.\n4. Add cooked pasta and toss. Add reserved pasta water as needed.\n5. Season with salt, pepper, red pepper flakes, and fresh basil.\n6. Top with grated Parmesan.",
        "ingredients": [
            {"name": "penne pasta", "quantity": 1, "unit": "lb"},
            {"name": "zucchini", "quantity": 1, "unit": None},
            {"name": "bell pepper", "quantity": 1, "unit": None},
            {"name": "cherry tomatoes", "quantity": 1, "unit": "cup"},
            {"name": "mushrooms", "quantity": 1, "unit": "cup"},
            {"name": "garlic", "quantity": 3, "unit": "cloves"},
            {"name": "olive oil", "quantity": 3, "unit": "tbsp"},
            {"name": "Parmesan cheese", "quantity": 0.25, "unit": "cup"},
        ],
    },
    {
        "name": "Grilled Burgers",
        "description": "Juicy homemade beef burgers with classic toppings.",
        "servings": 4,
        "prep_time": "10 minutes",
        "cook_time": "10 minutes",
        "tags": "dinner,grilling,kid-friendly,easy",
        "rating": 4,
        "instructions": "1. Mix ground beef with salt, pepper, garlic powder, and Worcestershire sauce.\n2. Form into 4 patties, slightly larger than buns (they shrink).\n3. Make a small indent in center of each patty.\n4. Grill over medium-high heat, 4-5 minutes per side for medium.\n5. Add cheese slices in the last minute to melt.\n6. Toast buns on the grill.\n7. Assemble with lettuce, tomato, onion, and condiments.",
        "ingredients": [
            {"name": "ground beef", "quantity": 1.5, "unit": "lbs"},
            {"name": "hamburger buns", "quantity": 4, "unit": None},
            {"name": "cheddar cheese", "quantity": 4, "unit": "slice"},
            {"name": "lettuce leaves", "quantity": 4, "unit": None},
            {"name": "tomato", "quantity": 1, "unit": None},
            {"name": "onion", "quantity": 1, "unit": None},
            {"name": "Worcestershire sauce", "quantity": 1, "unit": "tbsp"},
        ],
    },
    # === SNACK/DESSERT (3) ===
    {
        "name": "Hummus with Veggie Sticks",
        "description": "Creamy homemade hummus served with fresh cut vegetables.",
        "servings": 4,
        "prep_time": "10 minutes",
        "cook_time": "0 minutes",
        "tags": "snack,healthy,vegetarian,vegan,gluten-free,easy",
        "rating": 4,
        "instructions": "1. Drain and rinse chickpeas.\n2. Add chickpeas, tahini, lemon juice, garlic, and olive oil to a food processor.\n3. Blend until smooth, adding water as needed for desired consistency.\n4. Season with salt and cumin.\n5. Transfer to a bowl, drizzle with olive oil and paprika.\n6. Serve with carrot sticks, celery, cucumber, and bell pepper strips.",
        "ingredients": [
            {"name": "chickpeas", "quantity": 1, "unit": "can"},
            {"name": "tahini", "quantity": 2, "unit": "tbsp"},
            {"name": "lemon juice", "quantity": 2, "unit": "tbsp"},
            {"name": "garlic", "quantity": 1, "unit": "cloves"},
            {"name": "olive oil", "quantity": 2, "unit": "tbsp"},
            {"name": "carrots", "quantity": 2, "unit": None},
            {"name": "celery", "quantity": 2, "unit": None},
            {"name": "cucumber", "quantity": 1, "unit": None},
        ],
    },
    {
        "name": "Chocolate Chip Cookies",
        "description": "Classic chewy chocolate chip cookies.",
        "servings": 24,
        "prep_time": "15 minutes",
        "cook_time": "12 minutes",
        "tags": "dessert,kid-friendly,vegetarian,favorite",
        "rating": 5,
        "instructions": "1. Preheat oven to 375°F (190°C).\n2. Cream together softened butter and sugars until fluffy.\n3. Beat in eggs and vanilla.\n4. In a separate bowl, whisk flour, baking soda, and salt.\n5. Gradually mix dry ingredients into wet.\n6. Fold in chocolate chips.\n7. Drop rounded tablespoons onto lined baking sheets.\n8. Bake 10-12 minutes until edges are golden.\n9. Cool on pan 5 minutes, then transfer to wire rack.",
        "ingredients": [
            {"name": "butter", "quantity": 1, "unit": "cup"},
            {"name": "white sugar", "quantity": 0.75, "unit": "cup"},
            {"name": "brown sugar", "quantity": 0.75, "unit": "cup"},
            {"name": "eggs", "quantity": 2, "unit": None},
            {"name": "vanilla extract", "quantity": 1, "unit": "tsp"},
            {"name": "all-purpose flour", "quantity": 2.25, "unit": "cups"},
            {"name": "baking soda", "quantity": 1, "unit": "tsp"},
            {"name": "chocolate chips", "quantity": 2, "unit": "cups"},
        ],
    },
    {
        "name": "Trail Mix Energy Bites",
        "description": "No-bake energy bites packed with oats, peanut butter, and dried fruit.",
        "servings": 12,
        "prep_time": "15 minutes",
        "cook_time": "0 minutes",
        "tags": "snack,healthy,vegetarian,easy,meal-prep,kid-friendly",
        "rating": 4,
        "instructions": "1. Combine oats, peanut butter, honey, and vanilla in a large bowl.\n2. Stir in chocolate chips and dried cranberries.\n3. Refrigerate mixture for 15-30 minutes until firm enough to handle.\n4. Roll into 1-inch balls.\n5. Store in an airtight container in the refrigerator for up to 1 week.",
        "ingredients": [
            {"name": "rolled oats", "quantity": 1, "unit": "cup"},
            {"name": "peanut butter", "quantity": 0.5, "unit": "cup"},
            {"name": "honey", "quantity": 0.25, "unit": "cup"},
            {"name": "vanilla extract", "quantity": 1, "unit": "tsp"},
            {"name": "mini chocolate chips", "quantity": 0.25, "unit": "cup"},
            {"name": "dried cranberries", "quantity": 0.25, "unit": "cup"},
        ],
    },
]


def seed_starter_recipes() -> None:
    """Insert starter recipes if the recipes table is empty. No-op otherwise."""
    conn = get_connection()
    try:
        count = conn.execute("SELECT COUNT(*) FROM recipes").fetchone()[0]
        if count > 0:
            return
    finally:
        conn.close()

    from meal_planner.core import recipes as recipes_core

    for data in STARTER_RECIPES:
        ingredients = [
            RecipeIngredient(
                id=None, recipe_id=None,
                name=ing["name"],
                quantity=ing.get("quantity"),
                unit=ing.get("unit"),
            )
            for ing in data["ingredients"]
        ]
        recipe = Recipe(
            id=None,
            name=data["name"],
            description=data.get("description"),
            servings=data.get("servings", 4),
            prep_time=data.get("prep_time"),
            cook_time=data.get("cook_time"),
            instructions=data.get("instructions"),
            tags=data.get("tags"),
            rating=data.get("rating"),
            ingredients=ingredients,
        )
        recipes_core.add(recipe)
